version: '3.8'
services:
  gateway:
    build: gateway
#    image:
#    container_name:
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
#    image:
#    container_name:
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_SQL_INIT_MODE=always
      - SPRING_JPA_HIBERNATE_DDL-AUTO=none

  db:
    image: postgres:14.5-alpine
    container_name: postgres
    ports:
      - "6530:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=shareit